Modified home page - Arshdeep
AjitVerma15/Interactive-Portfolio pull request #6
Opened 2023-05-12 16:48 UTC by Arshdeep-13

# hello @AjitVerma15
I have modified your home page.

# Featues included:-
 1. Glowing effect
 2. Dark mode (enable by clicking on your name)

# Sample images:-
![s1](https://github.com/AjitVerma15/Interactive-Portfolio/assets/108752646/f9a98cea-163f-44ae-bf8d-487a26022ea9)
![s2](https://github.com/AjitVerma15/Interactive-Portfolio/assets/108752646/550ddb85-5381-4e3c-9d83-ab8ae4964ab9)

2023-05-13 16:31 UTC, AjitVerma15 requested changes

2023-05-13 16:31 UTC, AjitVerma15 commented on index.html
> +  <section id="Home">
Thanks @Arshdeep-13 For adding these features.
Dark mode is breaking in Home page
![image](https://github.com/AjitVerma15/Interactive-Portfolio/assets/53833570/dfe64913-7e10-4918-962d-7ad8df359f07)

2023-08-02 09:15 UTC, diomed commented
dark mode addition is very nice
but glowing effect, i think should not be official and should be your own personal preference here.

2025-01-13 07:04 UTC, AjitVerma15 commented
Already Added, Thanks @Arshdeep-13

2025-01-13 07:04 UTC, closed without merging